<?php

/**
 * Implements hook_theme().
 */
//function kendra_slider_theme($existing, $type, $theme, $path) {
//  return array();
//}

/**
 * Implements hook_field_widget_info().
 */
function kendra_slider_field_widget_info() {
  return array(
    'range_slider' => array(
      'label' => t('Slider'),
      'field types' => array('range_integer'),
      'settings' => array(),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function kendra_slider_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $element += array(
    '#type' => 'slider',
    '#default_value' => isset($items[$delta]) ? array('value' => $items[$delta]['from'],
      'value2' => $items[$delta]['to']) :
      array('value' => 0, 'value2' => 0),
    '#range' => TRUE,
  '#display_bubble' => TRUE,
  '#display_bubble_format' => '%{value}%||%{value}%',
  '#element_validate' => array('_kendra_slider_range_validate'),
  '#display_inputs' => FALSE,
  );
  return array('value' => $element);

}

function _kendra_slider_range_validate($element, &$form_state, $form) {
  // copy from slider values to range field array keys

  $from = $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['value']['value'];
  $to = $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['value']['value2'];

  if (!empty($from) || !empty($to)) {
   $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['from'] = $from;
   $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['to'] = $to;
  }
  else {
   $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['from'] = '';
   $form_state['values'][$element['#field_name']][$element['#language']][$element['#delta']]['to'] = '';
  }

  //dpm(get_defined_vars());
}


