<?php

/**
 * @file
 * Provide User access control and other functionality.
 */


/**
 * Implements hook_views_api().
 */
function kendra_user_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'kendra_user') . '/includes',
  );
}

/**
 * Checks if the curent user allowed to edit the asset.
 *
 * TRUE if user is is the owner of the asset page or user has kendra admin role.
 */
function kendra_user_can_user_edit_asset() {
  global $user;

  // If an admin or a kendra admin.
  if (in_array('kendra', $user->roles) | in_array('administrator', $user->roles)) {
    // Allays allow access.
    return TRUE;
  }

// If an Asset Author
if (in_array('Asset Author', $user->roles)) {
// check if a node page.
  If (arg(0) == 'node') {
    $node = node_load(arg(1));
    // Check if asset page.
    if ($node->type == 'asset') {
      // Return TRUE if same user.
      return ($node->uid == $user->uid);
    }
  }
}

// All other cases should return FALSE.
return FALSE;

}